remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: Your Blog Title
email: your-email@example.com
description: >- 
  블로그 설명을 여기에 적어주세요
baseurl: "/guma.github.io"
url: "https://johayoung227.github.io"
github_username: JoHaYoung227

# Build settings
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Theme settings
minimal_mistakes_skin: "default"