remote_theme: cotes2020/jekyll-theme-chirpy
#minimal_mistakes_skin: "default"

# Site Settings
locale: "ko-KR"
title: "GUMA"
title_separator: "-"
subtitle: ""
name: "GUMA"
description: "공부 기록"
url: "https://johayoung227.github.io"
baseurl: ""
repository: "JoHaYoung227/guma.github.io"

# Site Author
author:
  name: "Guma"
  bio: "대학원생"
  location: "South Korea"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true

# Outputting
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache