remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Site Settings
locale: "ko-KR"
title: "구마의 블로그"
title_separator: "-"
subtitle: "개발 일지"
name: "구마"
description: "개발 공부 기록"
url: "https://johayoung227.github.io"
baseurl: ""
repository: "JoHaYoung227/guma.github.io"

# Site Author
author:
  name: "구마"
  bio: "개발자"
  location: "South Korea"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache